import os
import sys
import webbrowser
import threading
import time
from app import create_app

# Verify Python version
if sys.version_info < (3, 12):
    print("Error: This application requires Python 3.12 or higher.")
    print(f"Current Python version: {sys.version}")
    sys.exit(1)

# Add virtual environment path
venv_path = os.path.join(os.path.dirname(__file__), 'venv')
python_path = os.path.join(venv_path, 'Scripts' if sys.platform == 'win32' else 'bin')
sys.path.insert(0, python_path)

class BrowserOpener:
    """Class to handle browser opening functionality"""
    
    @staticmethod
    def open_browser():
        """Open browser after a short delay"""
        time.sleep(2)
        webbrowser.open('http://127.0.0.1:5000')
        print("Browser opened. If it doesn't appear, please navigate to http://127.0.0.1:5000")

# Create the Flask application
app = create_app()

# This file is used by Azure App Service and local development
if __name__ == "__main__":
    # Check if browser should be opened (can be controlled via command line args)
    if len(sys.argv) > 1 and sys.argv[1] == '--browser':
        threading.Thread(target=BrowserOpener.open_browser).start()
    
    # Run the application
    debug_mode = os.environ.get('FLASK_DEBUG', 'True').lower() == 'true'
    print(f"Starting Health Tracker Application (Debug mode: {debug_mode})")
    print("Press CTRL+C to quit")
    app.run(debug=debug_mode)
# Generated by Copilot