"""
Main application module for the Health Tracker App
"""
import os
from app import create_app

class AppRunner:
    """
    Application runner class for managing the Flask application
    """
    def __init__(self):
        """Initialize the application runner"""
        self.app = create_app()

    def run(self):
        """
        Run the Flask application
        """
        # Get port from environment variable or default to 5000
        port = int(os.environ.get('PORT', 5000))
        
        # Get host from environment or default to 0.0.0.0
        host = os.environ.get('HOST', '0.0.0.0')
        
        # Run the application
        self.app.run(
            host=host,
            port=port,
            debug=self.app.config.get('DEBUG', False)
        )

# Create and run application
app = create_app()

if __name__ == '__main__':
    runner = AppRunner()
    runner.run()

# Generated by Copilot