import os
import sys

# Add virtual environment path
venv_path = os.path.join(os.path.dirname(__file__), 'venv')
python_path = os.path.join(venv_path, 'Scripts' if sys.platform == 'win32' else 'bin')
sys.path.insert(0, python_path)

from app import create_app

# Generated by Copilot
app = create_app()

if __name__ == '__main__':
    app.run(debug=True)