@echo off
:: Activate virtual environment
call venv\Scripts\activate.bat

:: Install or upgrade requirements
pip install -r requirements.txt

:: Run the application
python run.py

:: Generated by Copilot