from app import create_app
import webbrowser
import threading
import time

def open_browser():
    # 等待2秒后打开浏览器
    time.sleep(2)
    webbrowser.open('http://127.0.0.1:5000')

if __name__ == '__main__':
    # 创建一个线程来打开浏览器
    threading.Thread(target=open_browser).start()
    
    # 创建并运行应用
    app = create_app()
    app.run(debug=True)

# Generated by Copilot
