import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import get_config

# Initialize database
db = SQLAlchemy()

def create_app():
    # Initialize Flask app
    app = Flask(__name__)
    
    # Load configuration
    app.config.from_object(get_config())
    
    # Initialize database with app
    db.init_app(app)
    
    # Import models and routes after initializing db
    from . import models, routes
    
    # Register blueprints
    app.register_blueprint(routes.bp)
    
    # Ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass
    
    # Create the database tables if they don't exist
    with app.app_context():
        db.create_all()
    
    return app

# Do not create the app instance here
# Let it be created by the calling module
# Generated by Copilot