from datetime import datetime
from app import db

class HealthData(db.Model):
    __tablename__ = 'health_data'
    
    id = db.Column(db.Integer, primary_key=True)  # Unique identifier for each entry
    systolic = db.Column(db.Integer, nullable=False)  # Systolic blood pressure (high value)
    diastolic = db.Column(db.Integer, nullable=False)  # Diastolic blood pressure (low value)
    heart_rate = db.Column(db.Integer, nullable=False)  # Heart rate reading
    tags = db.Column(db.String(100), nullable=True)  # Tags for categorizing the entry
    timestamp = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)  # Timestamp for the entry
    
    @property
    def blood_pressure(self):
        # Provide backward compatibility for templates still using blood_pressure
        return f"{self.systolic}/{self.diastolic}"
    
    def __repr__(self):
        return f'<HealthData {self.id}: BP={self.systolic}/{self.diastolic}, HR={self.heart_rate}, Time={self.timestamp}>'

# Generated by Copilot