name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - refactor_with_copilot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate lowercase repo owner
        id: lowercase
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Generate Docker tag
        id: docker_tag
        run: echo "tag=run-${{ github.run_id }}-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.owner }}/health-tracker-app:${{ steps.docker_tag.outputs.tag }}

# Generated by Copilot